all:
  children:
    aws:
      hosts:
        aws-vm:
          ansible_host: 98.86.150.144
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

    huawei:
      hosts:
        huawei-vm:
          ansible_host: 101.44.3.178
          ansible_user: endava-admin
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

    azure:
      hosts:
        azure-vm:
          ansible_host: 137.116.32.161
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/azure_rsa
