apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 55.5.0
    helm:
      valueFiles: []
      values: |
        grafana:
          adminPassword: admin
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.example.com
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            additionalScrapeConfigs:
              - job_name: 'vm-node-exporter'
                scrape_interval: 30s
                static_configs:
                  - targets:
                      - '44.204.214.31:9100'
                    labels:
                      cloud: aws
                      instance_name: aws-vm
                  - targets:
                      - '20.110.132.161:9100'
                    labels:
                      cloud: azure
                      instance_name: azure-vm
                  - targets:
                      - '101.44.3.196:9100'
                    labels:
                      cloud: huawei
                      instance_name: huawei-vm
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
